#spring:
#  datasource:
#    url: jdbc:mysql://localhost/dataRegister?createDatabaseIfNotExist=true
#    username: root
#    password: root
#    driverClassName: com.mysql.cj.jdbc.Driver
#  jpa:
#      showSql: true
#
#      hibernate:
#        ddlAuto: update
#  session:
#    store:
#      type: jdbc
#    timeout: 60s
#
#    jdbc:
#      initializeSchema: always
#      tableName: spring_session
#
#  h2:
#    consoleEnabled: true
#
#
#
#
#
#
